// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api.Models.VBDi", b =>
                {
                    b.Property<int>("vbid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("vbid"));

                    b.Property<string>("chuyenvien")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("coquanbh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("file")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("filedinhkem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("files")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("loaivanban")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ngaybh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngaynhap")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nguoiduyet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nguoiky")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("noinhantext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("sobanphathanh")
                        .HasColumnType("int");

                    b.Property<string>("sokh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tinhtrang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("trichyeu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VBDiid")
                        .HasColumnType("int");

                    b.Property<string>("VBDiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("vbid");

                    b.ToTable("vanbandichitiet");
                });
#pragma warning restore 612, 618
        }
    }
}
